### ISSUE TITLE
Feature request: have ava-spec load ava itself.

### ISSUE THREAD

**Issue by F1LT3R** [sheerun/ava-spec#16]
I get the `no-unused-vars` error from XO/ESlint when using the define spec.

<img width="327" alt="screen shot 2018-03-11 at 1 12 52 am" src="https://user-images.githubusercontent.com/1218446/37250388-68a9ade0-24c9-11e8-92c4-9ef69130d9ec.png">

<img width="384" alt="screen shot 2018-03-11 at 1 14 13 am" src="https://user-images.githubusercontent.com/1218446/37250393-896bc540-24c9-11e8-94ee-a0b0b2d209aa.png">

If I do not import ava, eg:

```javascript
// import test from 'ava'
import {define} from 'ava-spec'

define('my feature', it => {
	it('should work', t => {
		t.pass()
	})
})
```

...then I get the follow console error when running ava.

```shell
/Users/al/repos/markdown-renderer/lib/parser.test.js:5
(0, _avaSpec.define)('my feature', it => {
                    ^

TypeError: (0 , _avaSpec.define) is not a function
    at Object.<anonymous> (/Users/al/repos/markdown-renderer/lib/parser.test.js:4:1)
    at Module._compile (module.js:662:30)
    at Module.replacementCompile (/Users/al/repos/markdown-renderer/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at extensions.(anonymous function) (/Users/al/repos/markdown-renderer/node_modules/require-precompiled/index.js:13:11)
    at /Users/al/repos/markdown-renderer/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/Users/al/repos/markdown-renderer/node_modules/ava/lib/process-adapter.js:100:4)
    at Object.<anonymous> (/Users/al/repos/markdown-renderer/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/al/repos/markdown-renderer/node_modules/ava/lib/test-worker.js:62:1)
    at Module._compile (module.js:662:30)
    at Module.replacementCompile (/Users/al/repos/markdown-renderer/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/al/repos/markdown-renderer/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
```

It would be nice if ava-spec loaded ava itself internally so I would not have to put `disable-eslint rules`  in front of each import of ava. Doing this for all tests across a codebase seems like a lot of grunt work.

**Comment by sheerun** [comment]
I already require ava at https://github.com/sheerun/ava-spec/blob/master/lib/index.js

**Comment by sheerun** [comment]
Also, ava-spec doesn't implement `define` but `describe`, that why you've got this issue.
